### PR TITLE
Upgrade to react 0.13.1

### PR DESCRIPTION
**Pull request by barrystaes**
Trivial. I had to because we wanted/needed to use `<CollapsableNav />` from

```
    "react-bootstrap": "^0.20.0",
    "react-router-bootstrap": "^0.12.1",
```

@sokra feel free to let me know if PR's like this one are not helping..

### CODE REVIEW

**Comment by barrystaes** [comment]
@sokra does react-proxy-loader support react v0.13.1 ?

**Comment by sokra** [comment]
Why closing?

**Comment by barrystaes** [comment]
I may have found a regression but had no time to look into that yet. 
Bug might not exist, or not be related to this at al. (sometimes item / list pages wont load)

**Comment by sokra** [comment]
ok... I take a look myself.

**Pull request closed without merging**
